server {
    listen 80;
    listen [::]:80;
    server_name arthome.ai www.arthome.ai;
    return 301 https://admin.arthome.ai$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name arthome.ai www.arthome.ai;

    ssl_certificate /etc/letsencrypt/live/track.arthome.ai/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/track.arthome.ai/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://admin.arthome.ai$request_uri;
}
