export const DEFAULT_CONVERSION_EVENT_TYPES = [
  { slug: 'viewcontent', displayLabel: 'ViewCONTENT revenue', sortOrder: 5 },
  { slug: 'click_button', displayLabel: 'Click Button revenue', sortOrder: 8 },
  { slug: 'call_click', displayLabel: 'Call click revenue', sortOrder: 9 },
  { slug: 'lead', displayLabel: 'Lead revenue', sortOrder: 10 },
  { slug: 'call_connected', displayLabel: 'Call Connected revenue', sortOrder: 14 },
  { slug: 'sale', displayLabel: 'Sales revenue', sortOrder: 20 },
  { slug: 'sales', displayLabel: 'Sales revenue', sortOrder: 21 },
  { slug: 'purchase', displayLabel: 'Purchase revenue', sortOrder: 30 },
  { slug: 'postalcode', displayLabel: 'PostalCode revenue', sortOrder: 50 },
  { slug: 'account_opening', displayLabel: 'account_opening revenue', sortOrder: 60 },
  { slug: 'account_validated', displayLabel: 'account_validated revenue', sortOrder: 70 },
  { slug: 'age_60', displayLabel: 'Age_60 revenue', sortOrder: 80 },
  { slug: 'hearing_loss', displayLabel: 'Hearing_loss revenue', sortOrder: 90 },
  { slug: 'test', displayLabel: 'test revenue', sortOrder: 100 },
];
